---
- name: install and start APACHE HTTPD
  hosts: zeeshanvm
  tasks: 

    - name: httpd package is present
      yum:
        name: httpd
        state: present
#SECOND TASK  
    - name: correct index.html is present
      copy: 
        src: files/index.html
        dest: /var/www/html/index.html
#THIRD TASK
    - name: httpd is started
      service: 
        name: httpd
        state: started
        enabled: true
